using Cake.Core.IO;
using Cake.Core.Tooling;
using System.Collections.Generic;

namespace Cake.DocFx.Merge
{
    /// <summary>
    /// Contains settings used by <see cref="DocFxMergeRunner"/>.
    /// </summary>
    public class DocFxMergeSettings : ToolSettings
    {
        /// <summary>
        /// Gets or sets the correlation id used for logging.
        /// </summary>
        public string CorrelationId { get; set; }

        /// <summary>
        /// Gets global metadata.
        /// It overrides the globalMetadata settings from the config file.
        /// See <see cref="DocFxGlobalMetadata"/> for constants for metadata keys.
        /// </summary>
        public IDictionary<string, string> GlobalMetadata { get; } = new Dictionary<string, string>();

        /// <summary>
        /// Gets or sets the path and file name where the log file generated by DocFx will be saved.
        /// </summary>
        public FilePath LogPath { get; set; }

        /// <summary>
        /// Gets or sets to which log level will be logged.
        /// </summary>
        public DocFxLogLevel LogLevel { get; set; }

        /// <summary>
        /// Gets or sets the Git repository root folder.
        /// </summary>
        public DirectoryPath RepositoryRoot { get; set; }
        
        /// <summary>
        /// Gets the TOC metadata names that need to be merged into the file.
        /// </summary>
        public IList<string> TocMetadata { get; } = new List<string>();

        /// <summary>
        /// Gets or sets a value indicating if warnings should be treated as errors.
        /// </summary>
        public bool WarningsAsErrors { get; set; }
    }
}
